import { registerItem } from "../ItemRegistry";

registerItem({ itemId: "stem", spriteName: "ss_sprite_005.png", maxStack: 64 });
registerItem({ itemId: "leaves", spriteName: "ss_sprite_006.png", maxStack: 64 });
registerItem({ itemId: "crop_residue", spriteName: "ss_sprite_007.png", maxStack: 64 });
registerItem({ itemId: "pods", spriteName: "ss_sprite_014.png", maxStack: 64 });
registerItem({ itemId: "soybean_oil", spriteName: "ss_sprite_016.png", maxStack: 64 });
registerItem({ itemId: "bagged_soybeans", spriteName: "ss_sprite_017.png", maxStack: 64 });
registerItem({ itemId: "flax_stalk", spriteName: "ss_sprite_022.png", maxStack: 64 });
registerItem({ itemId: "flax_fiber", spriteName: "ss_sprite_023.png", maxStack: 64 });
registerItem({ itemId: "thread", spriteName: "ss_sprite_024.png", maxStack: 64 });
registerItem({ itemId: "rope", spriteName: "ss_sprite_025.png", maxStack: 64 });
registerItem({ itemId: "cloth", spriteName: "ss_sprite_026.png", maxStack: 64 });
registerItem({ itemId: "bag", spriteName: "ss_sprite_027.png", maxStack: 64 });
registerItem({ itemId: "flaxseed_oil", spriteName: "ss_sprite_028.png", maxStack: 64 });
registerItem({ itemId: "trunk", spriteName: "ss_sprite_036.png", maxStack: 64 });
registerItem({ itemId: "charcoal", spriteName: "ss_sprite_082.png", maxStack: 64 });
registerItem({ itemId: "hot_meteoric_iron", spriteName: "ss_sprite_088.png", maxStack: 64 });
registerItem({ itemId: "blade", spriteName: "ss_sprite_084.png", maxStack: 64 });
registerItem({ itemId: "hardwood_teeth", spriteName: "ss_sprite_093.png", maxStack: 64 });
registerItem({ itemId: "board", spriteName: "ss_sprite_085.png", maxStack: 64 });
registerItem({ itemId: "screw_rod", spriteName: "ss_sprite_094.png", maxStack: 64 });
registerItem({ itemId: "shaft", spriteName: "ss_sprite_095.png", maxStack: 64 });
